# Petclinic DB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: petclinic-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          ports:
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: petclinic-mysql-user
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: petclinic-mysql-password
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: petclinic-mysql-root-password
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: petclinic-mysql-database
                  key: MYSQL_DATABASE
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "false"
        - containerPort: 3306
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "mysqladmin ping -h localhost"]
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "mysqladmin ping -h localhost"]
            initialDelaySeconds: 30
            timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: petclinic-prod
spec:
  type: ClusterIP  
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql